### ISSUE TITLE
XSS対策

### ISSUE THREAD

**Issue by yuhiwt** [iot-social-network-link/meetalk#36]
ニックネーム欄やメッセージ欄におけるスクリプト実行制御

例: `<script>alert("aaaaaaaaaaa")</script>`

関連記事：
http://qiita.com/sutetotanuki/items/5eda6bbb5532dd64529a
http://qiita.com/kimama1997/items/3c7d90681183faa7cfe4

**Comment by xkumiyu** [comment]
いわっちの関連記事にもあるけど、railsでは標準でXSS対策されている
みたいなので、おそらくrubyやhtmlのコードではなくjavascriptのコードで
問題があるのかも。

**Comment by matsu0228** [comment]
うん、特に無害化してないです
コントローラーで無害化するか、
jsで受け取る時に無害化するか
後で対応します！

**Comment by matsu0228** [comment]
・js側でユーザが入力した文字を扱う場合は、無害化してから利用する -> そのうち松木が修正します

ユーザ名を画面表示する
メッセージを表示するとき など
https://code4sec.com/yukisov/item/2ITFUFjeaGNb4aUGloMk#h2-4
encodeURIComponent()関数

**Comment by matsu0228** [comment]
下記にて修正済み
https://github.com/iot-social-network-link/meetalk/pull/53
