### ISSUE TITLE
roomへのuserid受け渡し

### ISSUE THREAD

**Issue by matsu0228** [iot-social-network-link/meetalk#43]
問題：現状はパラメータにユーザidを含んでしまっているため、セキュリティ的にNG
例)http://localhost:3000/room/2?user_id=5

案1) JSでPOSTリダイレクト
->/castingのコントローラでHTMLを返却する。そのHTML内にはPOSTリダイレクト処理を記述したJSを表示する
http://qiita.com/KurokoSin/items/b534c136fe2fb392c0db

案2)セッションIDをcookieに保存させ、userテーブルにセッションIDを保存する。
 ->クライアントからセッションIDをサーバに渡すことで、サーバ側でuserIDを特定する
 ->この場合、window idも不要になる？

**Comment by xkumiyu** [comment]
rails的にはセッション管理するのが標準かな。
セッションでログイン管理するイメージ。

**Comment by hirokoji** [comment]
ログイン入れるとなると次回の仕様に入れることになる？
あと、そもそも何のセキュリティー対策なのかも気になるなぁ。今ってデータベースにプライベートな情報がないから、
APIにauthenticationつけるだけでいいきもするなー。

**Comment by xkumiyu** [comment]
いや、ログインといってもユーザーの見た目は変わんないよ。
今までURLとかのパラメータでやりとりしていたのをセッションでやるだけ。

**Comment by hirokoji** [comment]
そういうことかぁ。それならシンプルでいいなぁ。

**Comment by xkumiyu** [comment]
その他のパラメータ受け渡し含め修正します。

**Comment by xkumiyu** [comment]
#45 で解決
