### ISSUE TITLE
テスト項目洗い出し

### ISSUE THREAD

**Issue by xkumiyu** [iot-social-network-link/meetalk#50]
単体テストは、コントローラーとモデルのテストをRspecで実施
結合テスト（フィーチャスペック）は、Rspec + Capybaraで実施

結合テストは、JavaScript側もあるので、洗い出しに協力ください。
Capybaraは、ブラウザ操作ができます。詳しくは、以下とかを見てください。
http://qiita.com/jnchito/items/607f956263c38a5fec24

現在のフィーチャスペック内容
- 操作内容
  - トップページに飛ぶ
  - 名前と性別を記入して、CAST NOWボタンを押す
- 確認内容
  - UserとRoomが新規作成されていること
  - 現在のページが/roomであること

追加予定
- roomページに時間表示されていること

テスト実行方法
- 全部実行

```
$ rspec
```
- フィーチャスペックのみ

```
$ rspec spec/features
```

**Comment by yuhiwt** [comment]
UTのスケジュール感にも依るけれど、洗い出すにあたって以下確認したいです。
- シナリオは現時点実装済のトップ→キャストのみ？マッチ/メッセージングも行う？
- カバレッジはc0:命令網羅、c1:分岐網羅程度？
- 正常系のみ？準正常？異常も含む？
- 対象端末・対象ブラウザや分岐部分のバリエーションはどこまでやる？

**Comment by xkumiyu** [comment]
> シナリオは現時点実装済のトップ→キャストのみ？マッチ/メッセージングも行う？

シナリオはとりあえずMVPまでいいと思う。
トップ→キャスト→マッチ→メッセージまでかな。
複数同時起動がテストでできるかわからんけど。。

> カバレッジはc0:命令網羅、c1:分岐網羅程度？

c0、c1ってなに？

> 正常系のみ？準正常？異常も含む？

とりあえず、正常系のみでいいかな？
異常系は単体テストでやる。

> 対象端末・対象ブラウザや分岐部分のバリエーションはどこまでやる？

Capybaraは標準だとFirefoxが起動される。
自動化するのは、まずはFirefoxのみで。
